version: "3.8"

services:
  quizapp:
    build: .
    container_name: quizzie-app
    ports:
      - "8080:8080"
    environment:
      - ENV=dev
      - QUESTION_PATH=https://github.com/stclaird/questionPack/releases/latest/download/questionPack-latest.zip
    volumes:
      - ../questionPack:/project/api/questionPack:ro
    restart: unless-stopped
    networks:
      - quizzie-network
networks:
  quizzie-network:
    driver: bridge
