version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - QUESTION_PATH=https://github.com/stclaird/quizzie.cloud/releases/latest/download/manifest.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/categories/"]
      interval: 5s
      timeout: 3s
      retries: 5
