version: "3.8"

services:
  quizapp:
    build: .
    container_name: quizzie-app
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - QUESTION_PATH=https://github.com/stclaird/questionPack/archive/refs/tags/0.1.zip
    volumes:
      - ./api/questionPack:/project/api/questionPack:ro
    restart: unless-stopped
    networks:
      - quizzie-network

networks:
  quizzie-network:
    driver: bridge
