package question

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"

	"github.com/gin-gonic/gin"
	"github.com/stclaird/quizzie.cloud/questionCreator/pkg/models"
	"github.com/stclaird/quizzie.cloud/questionCreator/pkg/util"
)

func createQuestion(ctx *gin.Context) {
	//Generate a question return as API response and write copy to file system
	config := ctx.MustGet("config").(util.Config)

	var questionDir = config.Questionsdir
    var questionIn models.QuestionIn
    if err := ctx.BindJSON(&questionIn); err != nil {
        ctx.JSON(400, gin.H{"error": err.Error()})
        return
    }

	var questionCategory string
	var questionSubCategory string

	questionTextSplit := splitString(questionIn.QuestionText)

	if questionIn.Category == "" {
		if len(questionTextSplit) > 0 {
			questionCategory = questionTextSplit[0]
		} else {
			questionCategory = "General"
		}
	} else {
		questionCategory = questionIn.Category
	}

	if questionIn.Subcategory == "" {
		if len(questionTextSplit) > 1 {
			questionSubCategory = questionTextSplit[1]
		} else if len(questionTextSplit) > 0 {
			questionSubCategory = questionTextSplit[0] + "-subcategory"
		} else {
			questionSubCategory = "General"
		}
	} else {
		questionSubCategory = questionIn.Subcategory
	}

    questionsOut := askAi(questionIn)

	// Check if AI returned any questions
	if len(questionsOut.Questions) == 0 {
		fmt.Printf("No questions generated by AI\n")
		ctx.JSON(500, gin.H{"error": "AI failed to generate questions"})
		return
	}

	fmt.Printf("AI generated %d questions\n", len(questionsOut.Questions))

	var questionsOutFile []models.QuestionOut

	for i := range questionsOut.Questions {

		questionOut := questionsOut.Questions[i]
        questionOut.Subcategory = questionSubCategory
		questionOut.Category = questionCategory
		questionOut.DateAdded = createDate()

		questionsOutFile = append(questionsOutFile, questionOut)

	}

	questionsOutFileBytes, err := json.Marshal(questionsOutFile)
	if err != nil {
		fmt.Printf("Error marshaling questions: %v\n", err)
		ctx.JSON(500, gin.H{"error": "Failed to marshal questions"})
		return
	}

    questionName := generateQuestionFileName(questionCategory, questionSubCategory )
	fmt.Printf("Creating directory: %s\n", questionDir)
	err = os.MkdirAll(questionDir, 0755)

	if err != nil {
		fmt.Printf("Error creating directory: %v\n", err)
		ctx.JSON(500, gin.H{"error": "Failed to create questions directory"})
		return
	}

	fmt.Printf("Writing File %s\n", questionName)
	var writeFileName = fmt.Sprintf("%s/%s", questionDir, questionName)
	fmt.Printf("Full path: %s\n", writeFileName)
	err = os.WriteFile(writeFileName, questionsOutFileBytes, os.ModePerm)
	if err != nil {
		fmt.Printf("Error writing file: %v\n", err)
		ctx.JSON(500, gin.H{"error": "Failed to write questions file"})
		return
	}
	fmt.Printf("Successfully wrote %d bytes to %s\n", len(questionsOutFileBytes), writeFileName)

    ctx.JSON(http.StatusOK, questionsOut)
}
